### ISSUE TITLE
The latest docker hub image has files [ and [[ in it.

### ISSUE THREAD

**Issue by miklosszegedi** [tianon/docker-bash#16]
![image](https://user-images.githubusercontent.com/26262030/70838994-92f96b80-1dbf-11ea-871b-84b843f2ed30.png)
imageID: docker-pullable://bash@sha256:293ac2e5c5be7722d6f4aa620c6451aea359eec1f2f6d5c0faef948b86e449cd

**Comment by tianon** [comment]
See the very relevant second half of the answer in https://github.com/tianon/docker-brew-ubuntu-core/issues/156#issuecomment-522785065 -- `[` and `[[` are shell utilities, and in this case the ones we have in `/usr/bin` come directly from our Alpine base image and if you check what they're symlinks to you'll see they're part of `busybox`:

```console
$ docker run -it --rm alpine:3.10
/ # help
Built-in commands:
------------------
	. : [ [[ alias bg break cd chdir command continue echo eval exec
	exit export false fg getopts hash help history jobs kill let
	local printf pwd read readonly return set shift source test times
	trap true type ulimit umask unalias unset wait
```

In a POSIX shell, `[` is typically an alias for the `test` built-in utility, and `[[` is typically a Bashism, but it's one that Busybox supports to a certain extent.

If you use either of `[` or `[[` from Bash, it will not invoke these versions from `/usr/bin` but will instead invoke its own built-in implementations of their functionality.
