### ISSUE TITLE
Also publish to alternative package registries

### ISSUE THREAD

**Issue by martin-schulze-vireso** [tianon/docker-bash#23]
I use your images in one of my (Travis) CI builds which started failing due to dockerhub's rate limit. I cannot work around that by using a login because it is a public project which receives external PRs that won't get the login credentials from Travis.

Could you republish your images on other registries like quay.io or ghcr.io, so we can move on?

**Comment by tianon** [comment]
I have no plans or intentions to push builds of this image to any registry.  I'd note that these other registries have rate limits as well, just perhaps less conspicuous ones.

I'd also add that I don't see issues with rate limiting from GitHub Actions (which I use quite extensively for Docker-related work), so that's maybe something to consider/try.

**Comment by martin-schulze-vireso** [comment]
Thanks for the fast reply.

> I'd note that these other registries have rate limits as well, just perhaps less conspicuous ones.

I did not find information about that. I only see limits on private repositories but that is not important for a public project.

> I'd also add that I don't see issues with rate limiting from GitHub Actions (which I use quite extensively for Docker-related work), so that's maybe something to consider/try.

For anonymous users the rate limiting is done per IP. I assume that Travis just has more traffic per IP than Github Actions. However, that may change in the future, leading to the same problem.

### Update

Okay, it sounds like Microsoft struck a deal with Docker hub [there](https://github.com/actions/virtual-environments/issues/1445#issuecomment-713861495):

> For publicly accessible containers we are working with docker hub to make sure you will not be impacted by the new rate limits. If you need private containers we still do not have a solution for that problem for forks of public repos.
