### ISSUE TITLE
Bash binary is at a non-standard location

### ISSUE THREAD

**Issue by av-2024** [tianon/docker-bash#29]

**Comment by tianon** [comment]
Yeah, this is unfortunate, but I'm not sure there's a great general-purpose solution.  If we install to `/bin/bash`, we risk being overridden explicitly or implicitly by the distribution's `bash` package. :see_no_evil:

(See also https://github.com/tianon/docker-bash/issues/9#issuecomment-376928024)

**Comment by avaranze** [comment]
Thank you. I appreciate the thoughtful response and link to more info.  Pardon my initial spicy comments.
