### ISSUE TITLE
Image pull fail on official docker bash

### ISSUE THREAD

**Issue by ehcmke** [tianon/docker-bash#36]
I started getting an image pull failure in my gitlab runner. I run this maybe monthly, last few months were fine.

my YAML had:

name: bash <---- original

tried
name: bash:latest <---- still failed
then
name: https://hub.docker.com/_/bash:latest

Trying another image worked so, it seems like something changed on this side. Do I need additional parameters?
![runner_fail](https://github.com/tianon/docker-bash/assets/72499661/78612423-4231-4de9-ab52-c1d36cb2e321)

**Comment by tianon** [comment]
It's probably that we've upgraded to OCI media types, if I had to guess without having quite enough information. :sweat_smile:

Are you using an up-to-date version of Docker?
