### ISSUE TITLE
amd64 version of 5.2.32 is missing

### ISSUE THREAD

**Issue by alok-runner** [tianon/docker-bash#39]
`bash:5.2.32@sha256:a78d2722a27547ce8b844c972bea4537c82ff97ad4bed3ee4d65689ba8cf53f9` is missing an amd64 version.

**Comment by tianon** [comment]
There was a hiccup with the downstream official build infrastructure, but
it's been resolved and builds are in progress! ❤️

**Comment by tianon** [comment]
Now fixed and published 👍
