### ISSUE TITLE
bad interpreter /bin/bash

### ISSUE THREAD

**Issue by setiseta** [tianon/docker-bash#9]
Hello,

I get an error, when i run a bash script inside this container with the default interpreter header line:
#!/bin/bash

I fixed it on my container with:
RUN ln -s $(which bash) /bin/bash

Maybe this can be done on official bash image?

**Comment by tianon** [comment]
I'd suggest instead changing your shebang to `#!/usr/bin/env bash` so it pulls `bash` from `$PATH` instead (which will also help users who compile a newer version of Bash than that provided by their distribution such as on Mac OS for example, which is also exactly what this image is doing inside Alpine Linux).

**Comment by setiseta** [comment]
Thanks for explanation.
This works.
